### ISSUE TITLE
Invalid Country Code mapping for SX Sint Maarten

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#17]
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#7568 for full details.

**Comment by KacperMadej** [comment]
After further investigation, we cannot have a duplicated `iso-a2` entry and since Sint Maarten is not on our maps then there is no conflict. In case we will be adding Sint Maarten the problem with already used SX hc-key should be resolved.

If you need to have this id changed please edit your map manually or use the demo from the full details link above.

Closing the issue for now.
