### ISSUE TITLE
Support ISO-3166-2 for regions

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#5]
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#5105 for full details.

**Comment by zeman** [comment]
@KacperMadej This issue was closed and marked as completed, but there is no support for ISO-3166-2 codes in the geo.json. There only appears to be support for HASC codes, which are only two letters and often different from ISO-3166-2 codes. HASC codes don't seem well maintained after the passing of Gwillim Law. Can I suggest this issue be reopened and support for ISO-3166-2 codes added to the geo.json files?

**Comment by hubertkozik** [comment]
Hi @zeman! My colleague has already answered the same question here: https://github.com/highcharts/map-collection-dist/issues/149#issuecomment-2255444809 Let's continue the discussion there :)

**Comment by KacperMadej** [comment]
_Side note:_
The title of this issue seems to be ambiguous and there are some redirects and longer discussions so to summarize this: the issue was about a limited list of maps and regions that was resolved map by map and then closed. For adding ISO 3166-2 to all maps see the issue linked in the above comment.
