### ISSUE TITLE
Dominican Republic: wrong province names

### ISSUE THREAD

**Issue by mekhatria** [highcharts/map-collection-dist#62]
[Highcharts Dominic Republic map](https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/do/do-all)
1. **Hermanas** should be **Hermanas Mirabal** 
2. **El Seybo** should be **El Seibo** 
3. **La Estrelleta** should be **Elias Piña**

Reference: [Wikipedia](https://simple.wikipedia.org/wiki/Provinces_of_the_Dominican_Republic)

**Comment by KacperMadej** [comment]
Thank you for reporting the wrong names.

Demo with the fixed names: https://jsfiddle.net/BlackLabel/oh5ebr7f/1/

**Comment by Johan-rosa** [comment]
Hi @KacperMadej,

The initial intention was to report the wrong names ([issue 62](https://github.com/highcharts/map-collection-dist/issues/62)), which are all right in the demo you provided. And, in order to point to the right names using an official source, I sent the link to the shapefiles, indicating the correct labels and saying that those shapefiles were more accurate.

Maybe I did not use the correct term, because the one you have right now are ok. I just though that using those would be an improvement, not knowing about resolution (and size, I think).

By the way, adding admin2 level map would be useful.  

Thanks for your help.

**Comment by Johan-rosa** [comment]
Now all names are ok. I am waiting for it to be in production. Thanks!!
